// Datos mock de productos sandalias (en producción vendrían de la API)
export const sandaliasProducts = {
  hawaii: {
    id: 'hawaii',
    title: 'Hawaii',
    slug: 'hawaii',
    subtitle: 'Sandalias Hawaii con detalles exóticos',
    description: 'Sandalias Hawaii con materiales exóticos. Diseño elegante y cómodo para la mujer moderna. Confeccionadas con los más finos materiales de pitón, estas sandalias combinan estilo y comodidad.',
    gender: 'mujer',
    material: 'pitón',
    height: 'sandalia',
    sku: 'LP-S-HWI',
    badge: 'Ladies',
    variants: [
      { 
        id: 'variant-1',
        name: 'Pitón rojo', 
        sku: 'LP-S-HWI-PITON-ROJO',
        priceMXN: 265000,
        stock: 50,
      },
      { 
        id: 'variant-2',
        name: 'Pitón natural', 
        sku: 'LP-S-HWI-PITON-NAT',
        priceMXN: 265000,
        stock: 50,
      },
    ],
    features: [
      'Material: Pitón exótico de primera calidad',
      'Forro: Cuero suave para máximo confort',
      'Suela: Cuero con diseño antideslizante',
      'Hecho a mano por artesanos expertos',
      'Garantía de calidad Leather Path',
    ],
    care: [
      'Limpiar con paño suave y seco',
      'Aplicar crema para cuero cada 3 meses',
      'Evitar contacto con agua',
      'Guardar en lugar fresco y seco',
    ],
  },
  bali: {
    id: 'bali',
    title: 'Bali',
    slug: 'bali',
    subtitle: 'Sandalias Bali con materiales exóticos',
    description: 'Sandalias Bali con materiales exóticos de avestruz y pitón. Diseño sofisticado que combina elegancia y comodidad para la mujer moderna.',
    gender: 'mujer',
    material: 'avestruz/pitón',
    height: 'sandalia',
    sku: 'LP-S-BAL',
    badge: 'Ladies',
    variants: [
      { 
        id: 'variant-1',
        name: 'Avestruz café', 
        sku: 'LP-S-BAL-AVES-CAF',
        priceMXN: 265000,
        stock: 50,
      },
      { 
        id: 'variant-2',
        name: 'Avestruz negro', 
        sku: 'LP-S-BAL-AVES-NGR',
        priceMXN: 265000,
        stock: 50,
      },
      { 
        id: 'variant-3',
        name: 'Negro y pitón natural', 
        sku: 'LP-S-BAL-PITON-MIX',
        priceMXN: 265000,
        stock: 50,
      },
    ],
    features: [
      'Material: Avestruz y pitón exótico',
      'Forro: Cuero suave para máximo confort',
      'Suela: Cuero con diseño antideslizante',
      'Hecho a mano por artesanos expertos',
      'Garantía de calidad Leather Path',
    ],
    care: [
      'Limpiar con paño suave y seco',
      'Aplicar crema para cuero cada 3 meses',
      'Evitar contacto con agua',
      'Guardar en lugar fresco y seco',
    ],
  },
  milo: {
    id: 'milo',
    title: 'Milo',
    slug: 'milo',
    subtitle: 'Sandalias Milo en cocodrilo',
    description: 'Sandalias Milo confeccionadas con piel de cocodrilo de primera calidad. Diseño elegante y sofisticado para la mujer que busca exclusividad.',
    gender: 'mujer',
    material: 'cocodrilo',
    height: 'sandalia',
    sku: 'LP-S-MIL',
    badge: 'Ladies',
    variants: [
      { 
        id: 'variant-1',
        name: 'Cocodrilo café', 
        sku: 'LP-S-MIL-COCO-CAF',
        priceMXN: 265000,
        stock: 50,
      },
    ],
    features: [
      'Material: Cocodrilo exótico de primera calidad',
      'Forro: Cuero suave para máximo confort',
      'Suela: Cuero con diseño antideslizante',
      'Hecho a mano por artesanos expertos',
      'Garantía de calidad Leather Path',
    ],
    care: [
      'Limpiar con paño suave y seco',
      'Aplicar crema para cuero cada 3 meses',
      'Evitar contacto con agua',
      'Guardar en lugar fresco y seco',
    ],
  },
  'bora-bora': {
    id: 'bora-bora',
    title: 'Bora Bora',
    slug: 'bora-bora',
    subtitle: 'Sandalias Bora Bora con estilo tropical',
    description: 'Sandalias Bora Bora con materiales exóticos y diseño tropical. Perfectas para la mujer que busca estilo y elegancia.',
    gender: 'mujer',
    material: 'pitón',
    height: 'sandalia',
    sku: 'LP-S-BRB',
    badge: 'Ladies',
    variants: [
      { 
        id: 'variant-1',
        name: 'Black Cherry', 
        sku: 'LP-S-BRB-BLACK-CH',
        priceMXN: 265000,
        stock: 50,
      },
      { 
        id: 'variant-2',
        name: 'Pitón azul mora', 
        sku: 'LP-S-BRB-PITON-AZM',
        priceMXN: 265000,
        stock: 50,
      },
    ],
    features: [
      'Material: Pitón exótico de primera calidad',
      'Forro: Cuero suave para máximo confort',
      'Suela: Cuero con diseño antideslizante',
      'Hecho a mano por artesanos expertos',
      'Garantía de calidad Leather Path',
    ],
    care: [
      'Limpiar con paño suave y seco',
      'Aplicar crema para cuero cada 3 meses',
      'Evitar contacto con agua',
      'Guardar en lugar fresco y seco',
    ],
  },
  mallorca: {
    id: 'mallorca',
    title: 'Mallorca',
    slug: 'mallorca',
    subtitle: 'Sandalias Mallorca con elegancia mediterránea',
    description: 'Sandalias Mallorca con materiales exóticos y diseño mediterráneo. Elegancia y sofisticación para la mujer moderna.',
    gender: 'mujer',
    material: 'pitón',
    height: 'sandalia',
    sku: 'LP-S-MLL',
    badge: 'Ladies',
    variants: [
      { 
        id: 'variant-1',
        name: 'Pitón natural', 
        sku: 'LP-S-MLL-PITON-NAT',
        priceMXN: 265000,
        stock: 50,
      },
      { 
        id: 'variant-2',
        name: 'Pitón coñac', 
        sku: 'LP-S-MLL-PITON-CON',
        priceMXN: 265000,
        stock: 50,
      },
    ],
    features: [
      'Material: Pitón exótico de primera calidad',
      'Forro: Cuero suave para máximo confort',
      'Suela: Cuero con diseño antideslizante',
      'Hecho a mano por artesanos expertos',
      'Garantía de calidad Leather Path',
    ],
    care: [
      'Limpiar con paño suave y seco',
      'Aplicar crema para cuero cada 3 meses',
      'Evitar contacto con agua',
      'Guardar en lugar fresco y seco',
    ],
  },
};

export function getProductBySlug(slug: string) {
  return sandaliasProducts[slug as keyof typeof sandaliasProducts] || null;
}

